### ISSUE TITLE
不支持windows吗?

### ISSUE THREAD

**Issue by FourTest** [tencentyun/cos-c-sdk-v5#9]
不支持windows吗?

**Comment by agin719** [comment]
> 不支持windows吗?

抱歉，目前不支持，windows可使用C++ SDK代替。 
https://cloud.tencent.com/document/product/436/12301#.E5.AE.89.E8.A3.85-windows-.E7.89.88.E6.9C.AC-sdk

**Comment by app910** [comment]
> 
> 
> > 不支持windows吗?
> 
> 抱歉，目前不支持，windows可使用C++ SDK代替。
> https://cloud.tencent.com/document/product/436/12301#.E5.AE.89.E8.A3.85-windows-.E7.89.88.E6.9C.AC-sdk

不行呀兄弟,这个c++SDK的也不支持windows.
号称支持windows,但是用了一堆的linux api呀,write  pthread_mutex_t  pthread_rwlock_t  lseek,完全编译不了啊.
这腾讯的开发是不是为了绩效什么的乱说一气的?

**Comment by app910** [comment]
> 
> 
> > 不支持windows吗?
> 
> 抱歉，目前不支持，windows可使用C++ SDK代替。
> https://cloud.tencent.com/document/product/436/12301#.E5.AE.89.E8.A3.85-windows-.E7.89.88.E6.9C.AC-sdk

他们这个c++的sdk大方承认不支持windows很难吗?

**Comment by agin719** [comment]
> > > 不支持windows吗?
> > 
> > 
> > 抱歉，目前不支持，windows可使用C++ SDK代替。
> > https://cloud.tencent.com/document/product/436/12301#.E5.AE.89.E8.A3.85-windows-.E7.89.88.E6.9C.AC-sdk
> 
> 他们这个c++的sdk大方承认不支持windows很难吗?

这个是做过测试才会发布出来的，如果编译遇到什么问题，可以到腾讯云提交相关工单，谢谢。
